backend:
  name: git-gateway
  branch: nextjs # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Cats'
            name: 'cats'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'TIL'
    label: 'Today I Learned'
    folder: 'content/TIL'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
